### ISSUE TITLE
links to anchors within page don't work for files in nested directories

### ISSUE THREAD

**Issue by xmojmr** [kennethjor/wintersmith-pandoc#11]
I have a markdown document in location 
`path\to\contents\subfolder-level-1\subfolder-level-2\markdown-syntax.md`

the file is just a copy of an article from the "blog" wintersmith example (..wintersmith\examples\blog\contents\articles\markdown-syntax\index.md)

When I build the site, **anchors from the table of contents get translated to totally wrong links**, e.g. original
```
[Overview](#overview)
```
becomes
```
<a href="/subfolder-level-1/subfolder-level-2/subfolder-level-1\subfolder-level-2\markdown-syntax.html#overview">Overview</a>
```

The issue gets fixed if I remove the link manipulating code in `plugin.coffee` function `getHtml` marked with comments *# handle links to anchors within the page* and *# handle relative links* altogether.

I'm using Windows version of pandoc.EXE 1.12.3

1. What is the purpose of the link manipulating code in getHtml?
2. Is some list of test cases (or unit tests) available that explains what should be solved by the code?
3. Is it still needed? (removing the code seems to fix my problem)

**Comment by kennethjor** [comment]
@xmojmr Hi, I'm the new maintainer of `wintersmith-pandoc`, and I'm doing a bit of housekeeping as part of taking over the project. Since this issue has been outstanding over a year without resolution, I'm going to go ahead and close it. If you're still having problem, feel free to re-open and I'll be happy to try and help you out.
