### ISSUE TITLE
Sporadic non-rendering

### ISSUE THREAD

**Issue by tlvince** [kennethjor/wintersmith-pandoc#3]
I haven't be able to pinpoint it further but sporadically (more often than not), I find pages are failing to render. Standalone `pandoc` renders the markdown fine and they are usually simple files. Have you experienced anything of the sort? This is primarily using Wintersmith's preview server.

**Comment by kennethjor** [comment]
@tlvince @MDCore Hi, I'm the new maintainer of `wintersmith-pandoc`, and I'm doing a bit of housekeeping as part of taking over the project. Since this issue has been outstanding over a year without resolution, I'm going to go ahead and close it. If you're still having problem, feel free to re-open and I'll be happy to try and help you out.
