### ISSUE TITLE
Is this plugin still working?

### ISSUE THREAD

**Issue by Sinetheta** [kennethjor/wintersmith-pandoc#7]
Fresh install of new wintersmith site. Install wintersmith-pandoc, add to config, preview site:

```
server running on: http://localhost:8080/

  error write EPIPE
```

**Comment by kennethjor** [comment]
@Sinetheta @acdlite Hi, I'm the new maintainer of `wintersmith-pandoc`, and I'm doing a bit of housekeeping as part of taking over the project. Since this issue has been outstanding over a year without resolution, I'm going to go ahead and close it. If you're still having problem, feel free to re-open and I'll be happy to try and help you out.
