### ISSUE TITLE
wrong image path render or worng version installed

### ISSUE THREAD

**Issue by lesar** [kennethjor/wintersmith-pandoc#9]
if I try to add image all work well on absolute url (http://www....)
but I do not know what will be the domain name and my work have to work well changing the domain name without touch md files.

so I use relative path:
>\!\[the image\](/images/image.png)
>or
>\!\[the image\](images/image.png)  

this two examples renders in <img src="//images/image.png" alt="...">
the double "//" do not work and browser do not show the image.  
If I remove wintersmith-pandoc all works well.  
I use ubuntu 13.04 64 bit
I have instal this plungin by
sudo npm install wintersmith-pandoc  
in the package.json I read:
  "name": "wintersmith-pandoc",
  "version": "0.2.0",
If I download your plug in I see that is version 0.2.1. 
Have I use bad commad to install wintersmith-pandoc?
Have I to some manual operation to install version 0.2.1 or this bug is active in last version too?  
best regards

**Comment by kennethjor** [comment]
@lesar Hi, I'm the new maintainer of `wintersmith-pandoc`, and I'm doing a bit of housekeeping as part of taking over the project. Since this issue has been outstanding over a year without resolution, I'm going to go ahead and close it. If you're still having problem, feel free to re-open and I'll be happy to try and help you out.
